CREATE TABLE board (
		id BIGSERIAL NOT NULL PRIMARY KEY,
		title VARCHAR(50) NOT NULL,
		content TEXT NOT NULL,
		filename VARCHAR(150),
		filepath VARCHAR(300)
);
--dummy data:
insert into board (id, title, content) values (1, 'Brightdog', '0 Caliangt Hill');
insert into board (id, title, content) values (2, 'Meejo', '8840 Thackeray Plaza');
insert into board (id, title, content) values (3, 'Topicstorm', '79 Birchwood Alley');
insert into board (id, title, content) values (4, 'Yata', '50 Boyd Street');
insert into board (id, title, content) values (5, 'Feedmix', '086 Helena Plaza');
insert into board (id, title, content) values (6, 'Skimia', '37942 Novick Lane');
insert into board (id, title, content) values (7, 'Chatterbridge', '368 Montana Terrace');
insert into board (id, title, content) values (8, 'Innotype', '953 Shopko Center');
insert into board (id, title, content) values (9, 'Twitterbridge', '1 Carey Road');
insert into board (id, title, content) values (10, 'Tagcat', '0539 Superior Trail');
insert into board (id, title, content) values (11, 'Aimbo', '37 Boyd Avenue');
insert into board (id, title, content) values (12, 'Topicware', '9 Hallows Terrace');
insert into board (id, title, content) values (13, 'Babbleblab', '1 Delladonna Circle');
insert into board (id, title, content) values (14, 'Snaptags', '583 Johnson Hill');
insert into board (id, title, content) values (15, 'Voomm', '77226 Mcguire Way');
insert into board (id, title, content) values (16, 'Wordify', '815 Bunting Terrace');
insert into board (id, title, content) values (17, 'Quinu', '92013 Mendota Point');
insert into board (id, title, content) values (18, 'Dynabox', '4009 Jenifer Circle');
insert into board (id, title, content) values (19, 'Jazzy', '02 John Wall Junction');
insert into board (id, title, content) values (20, 'Miboo', '17575 Wayridge Plaza');
insert into board (id, title, content) values (21, 'Zoomdog', '6115 Iowa Center');
insert into board (id, title, content) values (22, 'Browsecat', '2368 Crest Line Crossing');
insert into board (id, title, content) values (23, 'Riffpedia', '9830 Dottie Crossing');
insert into board (id, title, content) values (24, 'Feednation', '4397 Transport Court');
insert into board (id, title, content) values (25, 'Wikibox', '92101 Arapahoe Park');
insert into board (id, title, content) values (26, 'Tambee', '1 Bowman Pass');
insert into board (id, title, content) values (27, 'Yodo', '45628 Delladonna Place');
insert into board (id, title, content) values (28, 'Linkbuzz', '721 Spaight Junction');
insert into board (id, title, content) values (29, 'Devify', '42 Dottie Place');
insert into board (id, title, content) values (30, 'Omba', '02138 Jenifer Parkway');
insert into board (id, title, content) values (31, 'Devify', '0021 Anhalt Point');
insert into board (id, title, content) values (32, 'Edgeify', '363 Express Hill');
insert into board (id, title, content) values (33, 'Kare', '5 Mendota Street');
insert into board (id, title, content) values (34, 'Topiczoom', '043 Starling Crossing');
insert into board (id, title, content) values (35, 'Feedfire', '6 Tennyson Drive');
insert into board (id, title, content) values (36, 'Topiczoom', '84451 Golf View Hill');
insert into board (id, title, content) values (37, 'Quamba', '8742 Anhalt Circle');
insert into board (id, title, content) values (38, 'Jayo', '4495 Fieldstone Alley');
insert into board (id, title, content) values (39, 'Gabspot', '6619 Donald Hill');
insert into board (id, title, content) values (40, 'Blogtag', '4753 Bellgrove Circle');
insert into board (id, title, content) values (41, 'Fivebridge', '34 Marquette Hill');
insert into board (id, title, content) values (42, 'Voolith', '78 Hooker Junction');
insert into board (id, title, content) values (43, 'Browsecat', '24 Lillian Court');
insert into board (id, title, content) values (44, 'Eadel', '0 Wayridge Street');
insert into board (id, title, content) values (45, 'Shuffletag', '60 Rieder Way');
insert into board (id, title, content) values (46, 'Centidel', '76652 Hooker Plaza');
insert into board (id, title, content) values (47, 'Gigazoom', '6267 South Pass');
insert into board (id, title, content) values (48, 'Yombu', '730 Ruskin Place');
insert into board (id, title, content) values (49, 'Blogtags', '51258 Dahle Way');
insert into board (id, title, content) values (50, 'Kimia', '307 Emmet Way');
insert into board (id, title, content) values (51, 'Feedmix', '5 Darwin Way');
insert into board (id, title, content) values (52, 'Bubblemix', '79 Burning Wood Hill');
insert into board (id, title, content) values (53, 'Feedspan', '76 Carioca Avenue');
insert into board (id, title, content) values (54, 'Trudoo', '53 Morrow Street');
insert into board (id, title, content) values (55, 'Eayo', '05 Carioca Hill');
insert into board (id, title, content) values (56, 'Skynoodle', '27 Hagan Trail');
insert into board (id, title, content) values (57, 'Ailane', '026 Judy Road');
insert into board (id, title, content) values (58, 'Yakitri', '094 Laurel Park');
insert into board (id, title, content) values (59, 'Kwideo', '12 Laurel Street');
insert into board (id, title, content) values (60, 'DabZ', '05 Lien Street');
insert into board (id, title, content) values (61, 'Gabtune', '0 Algoma Lane');
insert into board (id, title, content) values (62, 'Camido', '82 Grim Road');
insert into board (id, title, content) values (63, 'Thoughtbridge', '9280 Vermont Way');
insert into board (id, title, content) values (64, 'Kwilith', '47246 Forest Road');
insert into board (id, title, content) values (65, 'Viva', '95 Golf View Junction');
insert into board (id, title, content) values (66, 'Meembee', '45629 Bluejay Hill');
insert into board (id, title, content) values (67, 'Mybuzz', '602 Commercial Place');
insert into board (id, title, content) values (68, 'Kwilith', '13281 High Crossing Pass');
insert into board (id, title, content) values (69, 'Jabbersphere', '11063 Rowland Terrace');
insert into board (id, title, content) values (70, 'Midel', '9 Mayer Junction');
insert into board (id, title, content) values (71, 'Voolith', '02206 Tennessee Place');
insert into board (id, title, content) values (72, 'Wordtune', '509 Fairview Circle');
insert into board (id, title, content) values (73, 'Photobug', '07803 Doe Crossing Circle');
insert into board (id, title, content) values (74, 'Voomm', '943 Hermina Lane');
insert into board (id, title, content) values (75, 'Topdrive', '024 Northland Avenue');
insert into board (id, title, content) values (76, 'Skynoodle', '25146 Hayes Pass');
insert into board (id, title, content) values (77, 'Npath', '0 Blue Bill Park Way');
insert into board (id, title, content) values (78, 'Skyndu', '381 Oxford Court');
insert into board (id, title, content) values (79, 'Twinte', '608 Kim Place');
insert into board (id, title, content) values (80, 'Omba', '13183 Cambridge Point');
insert into board (id, title, content) values (81, 'Aimbo', '2 Lukken Alley');
insert into board (id, title, content) values (82, 'Fliptune', '605 Del Mar Crossing');
insert into board (id, title, content) values (83, 'Vimbo', '7023 Surrey Lane');
insert into board (id, title, content) values (84, 'Shuffledrive', '278 Cottonwood Terrace');
insert into board (id, title, content) values (85, 'Oyoba', '7225 Helena Parkway');
insert into board (id, title, content) values (86, 'Babbleset', '8 Barnett Point');
insert into board (id, title, content) values (87, 'Tagpad', '666 Kipling Crossing');
insert into board (id, title, content) values (88, 'Zooxo', '259 Logan Terrace');
insert into board (id, title, content) values (89, 'Quatz', '813 Farmco Court');
insert into board (id, title, content) values (90, 'Jaloo', '222 6th Plaza');
insert into board (id, title, content) values (91, 'Lazzy', '5505 Kim Circle');
insert into board (id, title, content) values (92, 'Meemm', '661 Stone Corner Alley');
insert into board (id, title, content) values (93, 'Skyvu', '9923 Miller Street');
insert into board (id, title, content) values (94, 'Flashspan', '05106 Hauk Road');
insert into board (id, title, content) values (95, 'Buzzster', '8832 Golf View Circle');
insert into board (id, title, content) values (96, 'Rhynoodle', '286 Roth Way');
insert into board (id, title, content) values (97, 'Shufflester', '2163 Ridge Oak Court');
insert into board (id, title, content) values (98, 'Riffwire', '73 Crescent Oaks Terrace');
insert into board (id, title, content) values (99, 'Mita', '80 Westridge Park');
insert into board (id, title, content) values (100, 'Jetwire', '50 Maple Road');